services:
  community_benchmark:
    container_name: community_benchmark
    build:
      context: ./benchmark-tool
      dockerfile: Dockerfile
    command: /benchmark-tool community ${COMMUNITY_REPO_LINKS} --mysql-export
    environment:
      MYSQL_PASSWORD: S3cret_P@ssw0rd
      MYSQL_DATABASE: benchmark_repository
      MYSQL_ADDRESS: mysql_db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      GITHUB_TOKEN: ${GITHUB_TOKEN}
  mysql_db:
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: S3cret_P@ssw0rd
      MYSQL_DATABASE: benchmark_repository
      MYSQL_USER: benchmark
      MYSQL_PASSWORD: 123
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data:
